@startuml

enum Kategori {
    KOPI = 1,
    TEH = 2,
    DESERT = 3,
    SNACK = 4,
    MAKANAN = 5,
    LAINNYA = 6
}

class MenuOrder {
    - pilih[100] : int
    - jumlah[100] : int
    - sub_total[100] : int
    - harga[100] : int
    - menu[100] : string
    - total_bayar : int
    - i : int
    - selesai : bool

    + main() : int
}

MenuOrder --> Kategori : memilih Kategori
Kategori --> "1. KOPI"
Kategori --> "2. TEH"
Kategori --> "3. DESERT"
Kategori --> "4. SNACK"
Kategori --> "5. MAKANAN"
Kategori --> "6. LAINNYA"

MenuOrder --> "Tekan 0 jika selesai melakukan pemesanan"

while (!selesai) {
    MenuOrder --> Kategori : memilih Kategori Menu
    if (kategori_menu == 0) {
        MenuOrder --> "selesai"
    } else if (kategori_menu < KOPI || kategori_menu > LAINNYA) {
        MenuOrder --> "Kategori yang dipilih tidak valid!"
    }

    MenuOrder --> "Pilih Menu"
    if (kategori_menu == KOPI) {
        MenuOrder --> "1. ice caffe latte   Rp. 12000"
        MenuOrder --> "2. es kopi susu      Rp. 15000"
        MenuOrder --> "3. espresso         Rp. 18000"
        MenuOrder --> "4. ice cappucino    Rp. 17000"
        MenuOrder --> "5. hot cafee       Rp. 9000"
    } else if (kategori_menu == TEH) {
        MenuOrder --> "1. Tea jeruk (Es/panas)      Rp. 5000"
        MenuOrder --> "2. green tea (Es/panas)    Rp. 12000"
        MenuOrder --> "3. leci tea (Es/panas)    Rp. 13000"
    } else if (kategori_menu == DESERT) {
        MenuOrder --> "1. Choco heaven cake    Rp. 35000"
        MenuOrder --> "2. Cake tiramisu    Rp. 42000"
        MenuOrder --> "3. Banoffee  Rp. 33000"
    } else if (kategori_menu == MAKANAN) {
        MenuOrder --> "1. NASI GORENG      Rp. 15000"
        MenuOrder --> "2. INDOMIE    Rp. 9000"
    } else if (kategori_menu == SNACK) {
        MenuOrder --> "1. Cumi ring     Rp. 5000"
        MenuOrder --> "2. onnion ring  Rp. 12000"
        MenuOrder --> "3. kentang goreng    Rp. 13000"
    } else if (kategori_menu == LAINNYA) {
        MenuOrder --> "1. AQUA    Rp. 5000"
    }

    MenuOrder --> "Pilih Menu"
    if (kategori_menu == KOPI && menu_terpilih == 1) {
        MenuOrder --> "ice caffe latte"
        MenuOrder --> harga[i] = 12000
    } else if (kategori_menu == KOPI && menu_terpilih == 2) {
        MenuOrder --> "es kopi susu"
        MenuOrder --> harga[i] = 15000
    } else if (kategori_menu == KOPI && menu_terpilih == 3) {
        MenuOrder --> "espresso"
        MenuOrder --> harga[i] = 18000
    } else if (kategori_menu == KOPI && menu_terpilih == 4) {
        MenuOrder --> "ice cappucino"
        MenuOrder --> harga[i] = 17000
    } else if (kategori_menu == KOPI && menu_terpilih == 5) {
        MenuOrder --> "hot cafee"
        MenuOrder --> harga[i] = 9000
    } else if (kategori_menu == TEH && menu_terpilih == 1) {
        MenuOrder --> "Tea jeruk (Es/panas)"
        MenuOrder --> harga[i] = 5000
    } else if (kategori_menu == TEH && menu_terpilih == 2) {
        MenuOrder --> "green tea (Es/panas)"
        MenuOrder --> harga[i] = 12000
    } else if (kategori_menu == TEH && menu_terpilih == 3) {
        MenuOrder --> "leci tea (Es/panas)"
        MenuOrder --> harga[i] = 13000
    } else if (kategori_menu == DESERT && menu_terpilih == 1) {
        MenuOrder --> "Choco heaven cake"
        MenuOrder --> harga[i] = 35000
    } else if (kategori_menu == DESERT && menu_terpilih == 2) {
        MenuOrder --> "Cake tiramisu"
        MenuOrder --> harga[i] = 42000
    } else if (kategori_menu == DESERT && menu_terpilih == 3) {
        MenuOrder --> "Banoffee"
        MenuOrder --> harga[i] = 33000
    } else if (kategori_menu == MAKANAN && menu_terpilih == 1) {
        MenuOrder --> "NASI GORENG"
        MenuOrder --> harga[i] = 15000
    } else if (kategori_menu == MAKANAN && menu_terpilih == 2) {
        MenuOrder --> "INDOMIE"
        MenuOrder --> harga[i] = 9000
    } else if (kategori_menu == SNACK && menu_terpilih == 1) {
        MenuOrder --> "Cumi ring"
        MenuOrder --> harga[i] = 5000
    } else if (kategori_menu == SNACK && menu_terpilih == 2) {
        MenuOrder --> "onnion ring"
        MenuOrder --> harga[i] = 12000
    } else if (kategori_menu == SNACK && menu_terpilih == 3) {
        MenuOrder --> "kentang goreng"
        MenuOrder --> harga[i] = 13000
    } else if (kategori_menu == LAINNYA && menu_terpilih == 1) {
        MenuOrder --> "AQUA"
        MenuOrder --> harga[i] = 5000
    }

    MenuOrder --> "Jumlah Porsi"
    MenuOrder --> "Hitung Sub Total"
}

MenuOrder --> "INVOICE PEMBELIAN BAKSO SUKSES"

@enduml
